version: "3.7"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

  ui:
    build: ./vue-cli
    ports:
      - "5002:8080"
    volumes:
      - ./vue-cli:/app
      - /app/node_modules
