version: "3.7"
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
  ui:
    build: ./vue
    ports:
      - "5002:3000"
    volumes:
      - ./vue:/usr/src/app